modules.export.Record = [
  {"events":["carrot","exercise","weekend"],"activity":false},
  {"events":["bread","pudding","brushed teeth","weekend","touched tree"],"activity":false},
  {"events":["carrot","nachos","brushed teeth","cycling","weekend"],"activity":false},
  {"events":["brussel sprouts","ice cream","brushed teeth","computer","weekend"],"activity":false},
  {"events":["potatoes","candy","brushed teeth","exercise","weekend","dentist"],"activity":false},
  {"events":["brussel sprouts","pudding","brushed teeth","running","weekend"],"activity":false},
  {"events":["pizza","brushed teeth","computer","work","touched tree"],"activity":false},
  {"events":["bread","beer","brushed teeth","cycling","work"],"activity":false},
  {"events":["cauliflower","brushed teeth","work"],"activity":false},
  {"events":["pizza","brushed teeth","cycling","work"],"activity":false},
  {"events":["lasagna","nachos","brushed teeth","work"],"activity":false},
  {"events":["brushed teeth","weekend","touched tree"],"activity":false},
  {"events":["lettuce","brushed teeth","television","weekend"],"activity":false},
  {"events":["spaghetti","brushed teeth","work"],"activity":false},
  {"events":["brushed teeth","computer","work"],"activity":false},
  {"events":["lettuce","nachos","brushed teeth","work"],"activity":false},
  {"events":["carrot","brushed teeth","running","work"],"activity":false},
  {"events":["brushed teeth","work"],"activity":false},
  {"events":["cauliflower","reading","weekend"],"activity":false},
  {"events":["bread","brushed teeth","weekend"],"activity":false},
  {"events":["lasagna","brushed teeth","exercise","work"],"activity":false},
  {"events":["spaghetti","brushed teeth","reading","work"],"activity":false},
  {"events":["carrot","ice cream","brushed teeth","television","work"],"activity":false},
  {"events":["spaghetti","nachos","work"],"activity":false},
  {"events":["cauliflower","ice cream","brushed teeth","cycling","work"],"activity":false},
  {"events":["spaghetti","peanuts","computer","weekend"],"activity":true},
  {"events":["potatoes","ice cream","brushed teeth","computer","weekend"],"activity":false},
  {"events":["potatoes","ice cream","brushed teeth","work"],"activity":false},
  {"events":["peanuts","brushed teeth","running","work"],"activity":false},
  {"events":["potatoes","exercise","work"],"activity":false},
  {"events":["pizza","ice cream","computer","work"],"activity":false},
  {"events":["lasagna","ice cream","work"],"activity":false},
  {"events":["cauliflower","candy","reading","weekend"],"activity":false},
  {"events":["lasagna","nachos","brushed teeth","running","weekend"],"activity":false},
  {"events":["potatoes","brushed teeth","work"],"activity":false},
  {"events":["carrot","work"],"activity":false},
  {"events":["pizza","beer","work","dentist"],"activity":false},
  {"events":["lasagna","pudding","cycling","work"],"activity":false},
  {"events":["spaghetti","brushed teeth","reading","work"],"activity":false},
  {"events":["spaghetti","pudding","television","weekend"],"activity":false},
  {"events":["bread","brushed teeth","exercise","weekend"],"activity":false},
  {"events":["lasagna","peanuts","work"],"activity":true},
  {"events":["pizza","work"],"activity":false},
  {"events":["potatoes","exercise","work"],"activity":false},
  {"events":["brushed teeth","exercise","work"],"activity":false},
  {"events":["spaghetti","brushed teeth","television","work"],"activity":false},
  {"events":["pizza","cycling","weekend"],"activity":false},
  {"events":["carrot","brushed teeth","weekend"],"activity":false},
  {"events":["carrot","beer","brushed teeth","work"],"activity":false},
  {"events":["pizza","peanuts","candy","work"],"activity":true},
  {"events":["carrot","peanuts","brushed teeth","reading","work"],"activity":false},
  {"events":["potatoes","peanuts","brushed teeth","work"],"activity":false},
  {"events":["carrot","nachos","brushed teeth","exercise","work"],"activity":false},
  {"events":["pizza","peanuts","brushed teeth","television","weekend"],"activity":false},
  {"events":["lasagna","brushed teeth","cycling","weekend"],"activity":false},
  {"events":["cauliflower","peanuts","brushed teeth","computer","work","touched tree"],"activity":false},
  {"events":["lettuce","brushed teeth","television","work"],"activity":false},
  {"events":["potatoes","brushed teeth","computer","work"],"activity":false},
  {"events":["bread","candy","work"],"activity":false},
  {"events":["potatoes","nachos","work"],"activity":false},
  {"events":["carrot","pudding","brushed teeth","weekend"],"activity":false},
  {"events":["carrot","brushed teeth","exercise","weekend","touched tree"],"activity":false},
  {"events":["brussel sprouts","running","work"],"activity":false},
  {"events":["brushed teeth","work"],"activity":false},
  {"events":["lettuce","brushed teeth","running","work"],"activity":false},
  {"events":["candy","brushed teeth","work"],"activity":false},
  {"events":["brussel sprouts","brushed teeth","computer","work"],"activity":false},
  {"events":["bread","brushed teeth","weekend"],"activity":false},
  {"events":["cauliflower","brushed teeth","weekend"],"activity":false},
  {"events":["spaghetti","candy","television","work","touched tree"],"activity":false},
  {"events":["carrot","pudding","brushed teeth","work"],"activity":false},
  {"events":["lettuce","brushed teeth","work"],"activity":false},
  {"events":["carrot","ice cream","brushed teeth","cycling","work"],"activity":false},
  {"events":["pizza","brushed teeth","work"],"activity":false},
  {"events":["spaghetti","peanuts","exercise","weekend"],"activity":true},
  {"events":["bread","beer","computer","weekend","touched tree"],"activity":false},
  {"events":["brushed teeth","running","work"],"activity":false},
  {"events":["lettuce","peanuts","brushed teeth","work","touched tree"],"activity":false},
  {"events":["lasagna","brushed teeth","television","work"],"activity":false},
  {"events":["cauliflower","brushed teeth","running","work"],"activity":false},
  {"events":["carrot","brushed teeth","running","work"],"activity":false},
  {"events":["carrot","reading","weekend"],"activity":false},
  {"events":["carrot","peanuts","reading","weekend"],"activity":true},
  {"events":["potatoes","brushed teeth","running","work"],"activity":false},
  {"events":["lasagna","ice cream","work","touched tree"],"activity":false},
  {"events":["cauliflower","peanuts","brushed teeth","cycling","work"],"activity":false},
  {"events":["pizza","brushed teeth","running","work"],"activity":false},
  {"events":["lettuce","brushed teeth","work"],"activity":false},
  {"events":["bread","brushed teeth","television","weekend"],"activity":false},
  {"events":["cauliflower","peanuts","brushed teeth","weekend"],"activity":false}
];